/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace facebook::velox::wave {
void registerHeader(const char* text);
registerHeader("velox/experimental/wave/jit/BitUtils.cuh\n");
registerHeader(
    "velox/experimental/wave/jit/Scan.cuh\n"
    "\n"
    "#pragma once\n"
    "\n"
    "#include \"velox/experimental/wave/jit/BitUtil.cuh\"\n"
    "\n"
    "namespace facebook::velox::wave {\n"
    "\n"
    "template <typename T, int32_t kNumLanes = kWarpThreads>\n"
    "struct WarpScan {\n"
    "  enum {\n"
    "    /// Whether the logical warp size and the PTX warp size coincide\n"
    "    IS_ARCH_WARP = (kNumLanes == kWarpThreads),\n"
    "\n"
    "    /// The number of warp scan steps\n"
    "    STEPS = Log2<kNumLanes>::VALUE,\n"
    "\n"
    "    /// The 5-bit SHFL mask for logically splitting warps into sub-segments\n"
    "    /// starts 8-bits up\n"
    "    SHFL_C = (kWarpThreads - kNumLanes) << 8\n"
    "\n"
    "  };\n"
    "\n"
    "  static constexpr unsigned int member_mask =\n"
    "      kNumLanes == 32 ? 0xffffffff : (1 << kNumLanes) - 1;\n"
    "\n"
    "  WarpScan() = default;\n"
    "\n"
    "  __device__ __forceinline__ void exclusiveSum(\n"
    "      T input, ///< [in] Calling thread's input item.\n"
    "      T& exclusive_output) ///< [out] Calling thread's output item.  May be\n"
    "                           ///< aliased with \\p input.\n"
    "  {\n"
    "    T initial_value = 0;\n"
    "    exclusiveSum(input, exclusive_output, initial_value);\n"
    "  }\n"
    "\n"
    "  __device__ __forceinline__ void exclusiveSum(\n"
    "      T input, ///< [in] Calling thread's input item.\n"
    "      T& exclusive_output, ///< [out] Calling thread's output item.  May be\n"
    "                           ///< aliased with \\p input.\n"
    "      T initial_value) {\n"
    "    T inclusive_output;\n"
    "    inclusiveSum(input, inclusive_output);\n"
    "\n"
    "    exclusive_output = initial_value + inclusive_output - input;\n"
    "  }\n"
    "\n"
    "  __device__ __forceinline__ void ExclusiveSum(\n"
    "      T input, \n"
    "      T& exclusive_output, \n"
    "      T initial_value,\n"
    "      T& warp_aggregate) \n"
    "  {\n"
    "    T inclusive_output;\n"
    "    Inclusivesum(input, inclusive_output);\n"
    "    warp_aggregate = __shfl_sync(member_mask, inclusive_output, kNumLanes - 1);\n"
    "    exclusive_output = initial_value + inclusive_output - input;\n"
    "  }\n"
    "\n"
    "  __device__ __forceinline__ unsigned int inclusiveSumStep(\n"
    "      unsigned int input,\n"
    "      int first_lane, ///< [in] Index of first lane in segment\n"
    "      int offset) ///< [in] Up-offset to pull from\n"
    "  {\n"
    "    unsigned int output;\n"
    "    int shfl_c = first_lane | SHFL_C; // Shuffle control (mask and first-lane)\n"
    "\n"
    "    // Use predicate set from SHFL to guard against invalid peers\n"
    "    asm volatile(\n"
    "        \"{\"\n"
    "        \"  .reg .u32 r0;\"\n"
    "        \"  .reg .pred p;\"\n"
    "        \"  shfl.sync.up.b32 r0|p, %1, %2, %3, %5;\"\n"
    "        \"  @p add.u32 r0, r0, %4;\"\n"
    "        \"  mov.u32 %0, r0;\"\n"
    "        \"}\"\n"
    "        : \"=r\"(output)\n"
    "        : \"r\"(input), \"r\"(offset), \"r\"(shfl_c), \"r\"(input), \"r\"(member_mask));\n"
    "\n"
    "    return output;\n"
    "  }\n"
    "\n"
    "  __device__ __forceinline__ void inclusiveSum(\n"
    "      T input, \n"
    "      T& inclusive_output) {\n"
    "    inclusive_output = input;\n"
    "    int segment_first_lane = 0;\n"
    "#pragma unroll\n"
    "    for (int STEP = 0; STEP < STEPS; STEP++) {\n"
    "      inclusive_output = inclusiveSumStep(\n"
    "          inclusive_output, segment_first_lane, (1 << STEP));\n"
    "    }\n"
    "  }\n"
    "};\n"
    "\n"
    "} // namespace facebook::velox::wave\n");
registerHeader(
    "velox/experimental/wave/exec/WaveCore.cuh\n"
    "/*\n"
    "/* Copyright (c) Facebook, Inc. and its affiliates.\n"
    " *\n"
    " * Licensed under the Apache License, Version 2.0 (the \"License\");\n"
    " * you may not use this file except in compliance with the License.\n"
    " * You may obtain a copy of the License at\n"
    " *\n"
    " *     http://www.apache.org/licenses/LICENSE-2.0\n"
    " *\n"
    " * Unless required by applicable law or agreed to in writing, software\n"
    " * distributed under the License is distributed on an \"AS IS\" BASIS,\n"
    " * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
    " * See the License for the specific language governing permissions and\n"
    " * limitations under the License.\n"
    " */\n"
    "#pragma once\n"
    "\n"
    "#include \"velox/experimental/wave/jit/Scan.cuh\"\n"
    "#include \"velox/experimental/wave/exec/ExprKernel.h\"\n"
    "#include \"velox/experimental/wave/vector/Operand.h\"\n"
    "\n"
    "namespace facebook::velox::wave {\n"
    "\n"
    "template <typename T>\n"
    "inline T* __device__\n"
    "gridStatus(const WaveShared* shared, const InstructionStatus& status) {\n"
    "  return reinterpret_cast<T*>(\n"
    "      roundUp(\n"
    "          reinterpret_cast<uintptr_t>(\n"
    "              &shared->status\n"
    "                   [shared->numBlocks - (shared->blockBase / kBlockSize)]),\n"
    "          8) +\n"
    "      status.gridState);\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "inline T* __device__ laneStatus(\n"
    "    const WaveShared* shared,\n"
    "    const InstructionStatus& status,\n"
    "    int32_t nthBlock) {\n"
    "  return reinterpret_cast<T*>(\n"
    "      roundUp(\n"
    "          reinterpret_cast<uintptr_t>(shared->status) +\n"
    "              shared->numBlocks * sizeof(BlockStatus),\n"
    "          8) +\n"
    "      status.gridStateSize + status.blockState * shared->numBlocks);\n"
    "}\n"
    "\n"
    "inline bool __device__ laneActive(ErrorCode code) {\n"
    "  return static_cast<uint8_t>(code) <=\n"
    "      static_cast<uint8_t>(ErrorCode::kContinue);\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T& flatValue(void* base, int32_t blockBase) {\n"
    "  return reinterpret_cast<T*>(base)[blockBase + threadIdx.x];\n"
    "}\n"
    "\n"
    "/// Returns true if operand is non null. Sets 'value' to the value of the\n"
    "/// operand.\n"
    "template <typename T>\n"
    "__device__ __forceinline__ bool operandOrNull(\n"
    "    Operand** operands,\n"
    "    OperandIndex opIdx,\n"
    "    int32_t blockBase,\n"
    "    T& value) {\n"
    "  auto op = operands[opIdx];\n"
    "  int32_t index = threadIdx.x;\n"
    "  if (auto indicesInOp = op->indices) {\n"
    "    auto indices = indicesInOp[blockBase / kBlockSize];\n"
    "    if (indices) {\n"
    "      index = indices[index];\n"
    "      if (index == kNullIndex) {\n"
    "	return false;\n"
    "      }\n"
    "    } else {\n"
    "      index += blockBase;\n"
    "    }\n"
    "  } else {\n"
    "    index = (index + blockBase) & op->indexMask;\n"
    "  }\n"
    "  if (op->nulls && op->nulls[index] == kNull) {\n"
    "    return false;\n"
    "  }\n"
    "  value = reinterpret_cast<const T*>(op->base)[index];\n"
    "  return true;\n"
    "}\n"
    "\n"
    "template <bool kMayWrap, typename T>\n"
    "bool __device__ __forceinline__ valueOrNull(Operand** operands, OperandIndex opIdx, int32_t blockBase, T& value) {\n"
    "  auto op = operands[opIdx];\n"
    "  int32_t index = threadIdx.x;\n"
    "  if (!kMayWrap) {\n"
    "    index = (index + blockBase) & op->indexMask;\n"
    "    if (op->nulls && op->nulls[index] == kNull) {\n"
    "      return false;\n"
    "    }\n"
    "    value = reinterpret_cast<const T*>(op->base)[index];\n"
    "    return true;\n"
    "  }\n"
    "  if (auto indicesInOp = op->indices) {\n"
    "    auto indices = indicesInOp[blockBase / kBlockSize];\n"
    "    if (indices) {\n"
    "      index = indices[index];\n"
    "      if (index == kNullIndex) {\n"
    "	return false;\n"
    "      }\n"
    "} else {\n"
    "      index += blockBase;\n"
    "    }\n"
    "  } else {\n"
    "    index = (index + blockBase) & op->indexMask;\n"
    "  }\n"
    "  if (op->nulls && op->nulls[index] == kNull) {\n"
    "    return false;\n"
    "  }\n"
    "  value = reinterpret_cast<const T*>(op->base)[index];\n"
    "  return true;\n"
    "}\n"
    "\n"
    "template <bool kMayWrap, typename T>\n"
    "T __device__ __forceinline__ nonNullOperand(Operand** operands, OperandIndex opIdx, int32_t blockBase) {\n"
    "  auto op = operands[opIdx];\n"
    "  int32_t index = threadIdx.x;\n"
    "  if (!kMayWrap) {\n"
    "    index = (index + blockBase) & op->indexMask;\n"
    "    return reinterpret_cast<const T*>(op->base)[index];\n"
    "  }\n"
    "  if (auto indicesInOp = op->indices) {\n"
    "    auto indices = indicesInOp[blockBase / kBlockSize];\n"
    "    if (indices) {\n"
    "      index = indices[index];\n"
    "} else {\n"
    "      index += blockBase;\n"
    "    }\n"
    "  } else {\n"
    "    index = (index + blockBase) & op->indexMask;\n"
    "  }\n"
    "  return reinterpret_cast<const T*>(op->base)[index];\n"
    "}\n"
    "\n"
    "  \n"
    "bool __device__ __forceinline__ setRegisterNull(uint32_t& flags, int8_t bit, bool notNull) {\n"
    "  if (!notNull) {\n"
    "    flags &= ~(1 << bit);\n"
    "  }\n"
    "  return !notNull;\n"
    "}\n"
    "\n"
    "  bool __device__ __forceinline__ isRegisterNull(uint32_t flags, int8_t bit) {\n"
    "    return 0 == (flags & (1 << bit ));\n"
    "  }\n"
    "  \n"
    "template <typename T>\n"
    "__device__ inline T& flatOperand(\n"
    "    Operand** operands,\n"
    "    OperandIndex opIdx,\n"
    "    int32_t blockBase) {\n"
    "  auto* op = operands[opIdx];\n"
    "  if (op->nulls) {\n"
    "    op->nulls[blockBase + threadIdx.x] = kNotNull;\n"
    "  }\n"
    "  return reinterpret_cast<T*>(op->base)[blockBase + threadIdx.x];\n"
    "}\n"
    "\n"
    "\n"
    "  /// Clears 'bit' from 'flags' if notNull is false. Returns true if bit cleared.\n"
    "bool  __device__ __forceinline__ setNullRegister(uint32_t& flags, int8_t bit, bool notNull) {\n"
    "  if (!notNull) {\n"
    "    flags &= ~(1 << bit);\n"
    "  }\n"
    "  return !notNull;\n"
    "}\n"
    "\n"
    "/// Sets the lane's result to null for opIdx.\n"
    "__device__ inline void resultNull(\n"
    "    Operand** operands,\n"
    "    OperandIndex opIdx,\n"
    "    int32_t blockBase) {\n"
    "    auto* op = operands[opIdx];\n"
    "    op->nulls[blockBase + threadIdx.x] = kNull;\n"
    "  }\n"
    "\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T& flatResult(\n"
    "				Operand** operands,\n"
    "    OperandIndex opIdx,\n"
    "    int32_t blockBase) {\n"
    "  auto* op = operands[opIdx];\n"
    "  if (op->nulls) {\n"
    "    op->nulls[blockBase + threadIdx.x] = kNotNull;\n"
    "  }\n"
    "  return reinterpret_cast<T*>(op->base)[blockBase + threadIdx.x];\n"
    "}\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T& flatResult(Operand* op, int32_t blockBase) {\n"
    "  return flatResult<T>(&op, 0, blockBase);\n"
    "}\n"
    "\n"
    "#define PROGRAM_PREAMBLE(blockOffset)                                          \\\n"
    "  extern __shared__ char sharedChar[];                                         \\\n"
    "  WaveShared* shared = reinterpret_cast<WaveShared*>(sharedChar);              \\\n"
    "  int programIndex = params.programIdx[blockIdx.x + blockOffset];              \\\n"
    "  auto* program = params.programs[programIndex];                               \\\n"
    "  if (threadIdx.x == 0) {                                                      \\\n"
    "    shared->operands = params.operands[programIndex];                          \\\n"
    "    shared->status = &params.status                                            \\\n"
    "                          [blockIdx.x + blockOffset -                          \\\n"
    "                           params.blockBase[blockIdx.x + blockOffset]];        \\\n"
    "    shared->numRows = shared->status->numRows;                                 \\\n"
    "    shared->blockBase = (blockIdx.x + blockOffset -                            \\\n"
    "                         params.blockBase[blockIdx.x + blockOffset]) *         \\\n"
    "        blockDim.x;                                                            \\\n"
    "    shared->states = params.operatorStates[programIndex];                      \\\n"
    "    shared->numBlocks = params.numBlocks;                                      \\\n"
    "    shared->numRowsPerThread = params.numRowsPerThread;                        \\\n"
    "    shared->streamIdx = params.streamIdx;                                      \\\n"
    "    shared->isContinue = params.startPC != nullptr;                            \\\n"
    "    shared->hasContinue = false;                                               \\\n"
    "    shared->stop = false;                                                      \\\n"
    "  }                                                                            \\\n"
    "  __syncthreads();                                                             \\\n"
    "  auto blockBase = shared->blockBase;                                          \\\n"
    "  auto operands = shared->operands;                                            \\\n"
    "  ErrorCode laneStatus;                                                        \\\n"
    "  Instruction* instruction;                                                    \\\n"
    "  if (!shared->isContinue) {                                                   \\\n"
    "    instruction = program->instructions;                                       \\\n"
    "    laneStatus =                                                               \\\n"
    "        threadIdx.x < shared->numRows ? ErrorCode::kOk : ErrorCode::kInactive; \\\n"
    "  } else {                                                                     \\\n"
    "    auto start = params.startPC[programIndex];                                 \\\n"
    "    if (start == ~0) {                                                         \\\n"
    "      return; /* no continue in this program*/                                 \\\n"
    "    }                                                                          \\\n"
    "    instruction = program->instructions + start;                               \\\n"
    "    laneStatus = shared->status->errors[threadIdx.x];                          \\\n"
    "  }\n"
    "\n"
    "#define GENERATED_PREAMBLE(blockOffset)                                          \\\n"
    "  extern __shared__ char sharedChar[];                                         \\\n"
    "  WaveShared* shared = reinterpret_cast<WaveShared*>(sharedChar);              \\\n"
    "  int programIndex = params.programIdx[blockIdx.x + blockOffset];              \\\n"
    "  if (threadIdx.x == 0) {                                                      \\\n"
    "    shared->operands = params.operands[programIndex];                          \\\n"
    "    shared->status = &params.status                                            \\\n"
    "                          [blockIdx.x + blockOffset -                          \\\n"
    "                           params.blockBase[blockIdx.x + blockOffset]];        \\\n"
    "    shared->numRows = shared->status->numRows;                                 \\\n"
    "    shared->blockBase = (blockIdx.x + blockOffset -                            \\\n"
    "                         params.blockBase[blockIdx.x + blockOffset]) *         \\\n"
    "        blockDim.x;                                                            \\\n"
    "    shared->states = params.operatorStates[programIndex];                      \\\n"
    "    shared->numBlocks = params.numBlocks;                                      \\\n"
    "    shared->numRowsPerThread = params.numRowsPerThread;                        \\\n"
    "    shared->streamIdx = params.streamIdx;                                      \\\n"
    "    shared->isContinue = params.startPC != nullptr;                            \\\n"
    "    shared->extraWraps = params.extraWraps; \\\n"
    "    shared.numExtraWraps = params.numExtraWraps; \\\n"
    "shared->hasContinue = false;                                               \\\n"
    "    shared->stop = false;                                                      \\\n"
    "  }                                                                            \\\n"
    "  __syncthreads();                                                             \\\n"
    "  auto blockBase = shared->blockBase;                                          \\\n"
    "  auto operands = shared->operands;                                            \\\n"
    "  ErrorCode laneStatus;                                                        \\\n"
    "  int32_t entryPoint = 0; \\\n"
    "  if (!shared->isContinue) {						\\\n"
    "    laneStatus =                                                               \\\n"
    "        threadIdx.x < shared->numRows ? ErrorCode::kOk : ErrorCode::kInactive; \\\n"
    "  } else {                                                                     \\\n"
    "    entryPoint = params.startPC[programIndex];                                 \\\n"
    "    if (entryPoint == ~0) {                                                         \\\n"
    "      return; /* no continue in this program*/                                 \\\n"
    "    }                                                                          \\\n"
    "    laneStatus = shared->status->errors[threadIdx.x];                          \\\n"
    "  }\n"
    "\n"
    "\n"
    "#define PROGRAM_EPILOGUE()                          \\\n"
    "  if (threadIdx.x == 0) {                           \\\n"
    "    shared->status->numRows = shared->numRows;      \\\n"
    "  }                                                 \\\n"
    "  shared->status->errors[threadIdx.x] = laneStatus; \\\n"
    "  __syncthreads();\n"
    "\n"
    "__device__ __forceinline__ void filterKernel(\n"
    "    const IFilter& filter,\n"
    "    Operand** operands,\n"
    "    int32_t blockBase,\n"
    "    WaveShared* shared,\n"
    "    ErrorCode& laneStatus) {\n"
    "  bool isPassed = laneActive(laneStatus);\n"
    "  if (isPassed) {\n"
    "    if (!operandOrNull(\n"
    "            operands, filter.flags, blockBase, isPassed)) {\n"
    "      isPassed = false;\n"
    "    }\n"
    "  }\n"
    "  uint32_t bits = __ballot_sync(0xffffffff, isPassed);\n"
    "  if ((threadIdx.x & (kWarpThreads - 1)) == 0) {\n"
    "    reinterpret_cast<int32_t*>(&shared->data)[threadIdx.x / kWarpThreads] =\n"
    "        __popc(bits);\n"
    "  }\n"
    "  __syncthreads();\n"
    "  if (threadIdx.x < kWarpThreads) {\n"
    "    constexpr int32_t kNumWarps = kBlockSize / kWarpThreads;\n"
    "    uint32_t cnt = threadIdx.x < kNumWarps\n"
    "        ? reinterpret_cast<int32_t*>(&shared->data)[threadIdx.x]\n"
    "        : 0;\n"
    "    uint32_t sum;\n"
    "    using Scan = WarpScan<uint32_t, kBlockSize / kWarpThreads>;\n"
    "    Scan().exclusiveSum(cnt, sum);\n"
    "    if (threadIdx.x < kNumWarps) {\n"
    "      if (threadIdx.x == kNumWarps - 1) {\n"
    "        shared->numRows = cnt + sum;\n"
    "      }\n"
    "      reinterpret_cast<int32_t*>(&shared->data)[threadIdx.x] = sum;\n"
    "    }\n"
    "  }\n"
    "  __syncthreads();\n"
    "  if (bits & (1 << (threadIdx.x & (kWarpThreads - 1)))) {\n"
    "    auto* indices = reinterpret_cast<int32_t*>(operands[filter.indices]->base);\n"
    "    auto start = blockBase +\n"
    "        reinterpret_cast<int32_t*>(&shared->data)[threadIdx.x / kWarpThreads];\n"
    "    auto bit = start +\n"
    "        __popc(bits & lowMask<uint32_t>(threadIdx.x & (kWarpThreads - 1)));\n"
    "    indices[bit] = blockBase + threadIdx.x;\n"
    "  }\n"
    "  laneStatus =\n"
    "      threadIdx.x < shared->numRows ? ErrorCode::kOk : ErrorCode::kInactive;\n"
    "  __syncthreads();\n"
    "}\n"
    "\n"
    "__device__ __forceinline__ void filterKernel(\n"
    "    bool flag,\n"
    "    Operand** operands,\n"
    "    OperandIndex indicesIdx,\n"
    "int32_t blockBase,\n"
    "    WaveShared* shared,\n"
    "    ErrorCode& laneStatus) {\n"
    "  bool isPassed = flag && laneActive(laneStatus);\n"
    "  uint32_t bits = __ballot_sync(0xffffffff, isPassed);\n"
    "  if ((threadIdx.x & (kWarpThreads - 1)) == 0) {\n"
    "    reinterpret_cast<int32_t*>(&shared->data)[threadIdx.x / kWarpThreads] =\n"
    "        __popc(bits);\n"
    "  }\n"
    "  __syncthreads();\n"
    "  if (threadIdx.x < kWarpThreads) {\n"
    "    constexpr int32_t kNumWarps = kBlockSize / kWarpThreads;\n"
    "        uint32_t cnt = threadIdx.x < kNumWarps\n"
    "        ? reinterpret_cast<int32_t*>(&shared->data)[threadIdx.x]\n"
    "        : 0;\n"
    "    uint32_t sum;\n"
    "    using Scan = WarpScan<uint32_t, kBlockSize / kWarpThreads>;\n"
    "    Scan().exclusiveSum(cnt, sum);\n"
    "    if (threadIdx.x < kNumWarps) {\n"
    "      if (threadIdx.x == kNumWarps - 1) {\n"
    "        shared->numRows = cnt + sum;\n"
    "      }\n"
    "      reinterpret_cast<int32_t*>(&shared->data)[threadIdx.x] = sum;\n"
    "    }\n"
    "  }\n"
    "  __syncthreads();\n"
    "  if (bits & (1 << (threadIdx.x & (kWarpThreads - 1)))) {\n"
    "    auto* indices = reinterpret_cast<int32_t*>(operands[indicesIdx]->base);\n"
    "    auto start = blockBase +\n"
    "        reinterpret_cast<int32_t*>(&shared->data)[threadIdx.x / kWarpThreads];\n"
    "    auto bit = start +\n"
    "        __popc(bits & lowMask<uint32_t>(threadIdx.x & (kWarpThreads - 1)));\n"
    "    indices[bit] = blockBase + threadIdx.x;\n"
    "  }\n"
    "  laneStatus =\n"
    "      threadIdx.x < shared->numRows ? ErrorCode::kOk : ErrorCode::kInactive;\n"
    "  __syncthreads();\n"
    "}\n"
    "\n"
    "\n"
    "__device__ void __forceinline__ wrapKernel(\n"
    "    const IWrap& wrap,\n"
    "    Operand** operands,\n"
    "    int32_t blockBase,\n"
    "    int32_t numRows,\n"
    "    void* shared) {\n"
    "  Operand* op = operands[wrap.indices];\n"
    "  auto* filterIndices = reinterpret_cast<int32_t*>(op->base);\n"
    "  if (filterIndices[blockBase + numRows - 1] == numRows + blockBase - 1) {\n"
    "    // There is no cardinality change.\n"
    "    return;\n"
    "  }\n"
    "\n"
    "  struct WrapState {\n"
    "    int32_t* indices;\n"
    "  };\n"
    "\n"
    "  auto* state = reinterpret_cast<WrapState*>(shared);\n"
    "  bool rowActive = threadIdx.x < numRows;\n"
    "  for (auto column = 0; column < wrap.numColumns; ++column) {\n"
    "    if (threadIdx.x == 0) {\n"
    "      auto opIndex = wrap.columns[column];\n"
    "      auto* op = operands[opIndex];\n"
    "      int32_t** opIndices = &op->indices[blockBase / kBlockSize];\n"
    "      if (!*opIndices) {\n"
    "        *opIndices = filterIndices + blockBase;\n"
    "        state->indices = nullptr;\n"
    "      } else {\n"
    "        state->indices = *opIndices;\n"
    "      }\n"
    "    }\n"
    "    __syncthreads();\n"
    "    // Every thread sees the decision on thred 0 above.\n"
    "    if (!state->indices) {\n"
    "      continue;\n"
    "    }\n"
    "    int32_t newIndex;\n"
    "    if (rowActive) {\n"
    "      newIndex =\n"
    "          state->indices[filterIndices[blockBase + threadIdx.x] - blockBase];\n"
    "    }\n"
    "    // All threads hit this.\n"
    "    __syncthreads();\n"
    "    if (rowActive) {\n"
    "      state->indices[threadIdx.x] = newIndex;\n"
    "    }\n"
    "  }\n"
    "  __syncthreads();\n"
    "}\n"
    "\n"
    "__device__ void __forceinline__ wrapKernel(\n"
    "					   OperandIndex* wraps,\n"
    "					   int32_t numWraps,\n"
    "					   OperandIndex indicesIdx,\n"
    "					   Operand** operands,\n"
    "    int32_t blockBase,\n"
    "					   WaveShared* shared) {\n"
    "  Operand* op = operands[indicesIdx];\n"
    "  auto* filterIndices = reinterpret_cast<int32_t*>(op->base);\n"
    "  if (filterIndices[blockBase + shared->numRows - 1] == shared->numRows + blockBase - 1) {\n"
    "    // There is no cardinality change.\n"
    "    return;\n"
    "  }\n"
    "\n"
    "  struct WrapState {\n"
    "    int32_t* indices;\n"
    "  };\n"
    "\n"
    "  auto* state = reinterpret_cast<WrapState*>(&shared->data);\n"
    "  bool rowActive = threadIdx.x < shared->numRows;\n"
    "  int32_t totalWrap = numWraps + shared->numExtraWraps;\n"
    "  for (auto column = 0; column < totalWrap; ++column) {\n"
    "    if (threadIdx.x == 0) {\n"
    "      auto opIndex = column < numWraps ? wraps[column] : shared->extraWraps + column - numWraps;\n"
    "      auto* op = operands[opIndex];\n"
    "      int32_t** opIndices = &op->indices[blockBase / kBlockSize];\n"
    "      if (!*opIndices) {\n"
    "        *opIndices = filterIndices + blockBase;\n"
    "        state->indices = nullptr;\n"
    "      } else {\n"
    "        state->indices = *opIndices;\n"
    "      }\n"
    "    }\n"
    "    __syncthreads();\n"
    "    // Every thread sees the decision on thred 0 above.\n"
    "    if (!state->indices) {\n"
    "      continue;\n"
    "    }\n"
    "    int32_t newIndex;\n"
    "    if (rowActive) {\n"
    "      newIndex =\n"
    "          state->indices[filterIndices[blockBase + threadIdx.x] - blockBase];\n"
    "    }\n"
    "    // All threads hit this.\n"
    "    __syncthreads();\n"
    "    if (rowActive) {\n"
    "      state->indices[threadIdx.x] = newIndex;\n"
    "    }\n"
    "  }\n"
    "  __syncthreads();\n"
    "}\n"
    "\n"
    "\n"
    "template <typename T>\n"
    "__device__ inline T opFunc_kPlus(T left, T right) {\n"
    "  return left + right;\n"
    "}\n"
    "\n"
    "template <typename T, typename OpFunc>\n"
    "__device__ __forceinline__ void binaryOpKernel(\n"
    "    OpFunc func,\n"
    "    IBinary& instr,\n"
    "    Operand** operands,\n"
    "    int32_t blockBase,\n"
    "    void* shared,\n"
    "    ErrorCode& laneStatus) {\n"
    "  if (!laneActive(laneStatus)) {\n"
    "    return;\n"
    "  }\n"
    "  T left;\n"
    "  T right;\n"
    "  if (operandOrNull(operands, instr.left, blockBase, left) &&\n"
    "      operandOrNull(operands, instr.right, blockBase, right)) {\n"
    "    flatResult<decltype(func(left, right))>(\n"
    "        operands, instr.result, blockBase) = func(left, right);\n"
    "  } else {\n"
    "    resultNull(operands, instr.result, blockBase);\n"
    "  }\n"
    "}\n"
    "\n"
    "  template <typename T>\n"
    "  __device__ T value(Operand* operands, OperandIndex opIdx) {\n"
    "    // Obsolete signature. call sites must be changed.\n"
    "    //    assert(false);\n"
    "    *(long*)0 = 0;\n"
    "    return T{};\n"
    "  }\n"
    "  \n"
    "} // namespace facebook::velox::wave\n");
registerHeader(
    "velox/experimental/wave/exec/ExprKernel.h\n"
    "/*\n"
    " * Copyright (c) Facebook, Inc. and its affiliates.\n"
    " *\n"
    " * Licensed under the Apache License, Version 2.0 (the \"License\");\n"
    " * you may not use this file except in compliance with the License.\n"
    " * You may obtain a copy of the License at\n"
    " *\n"
    " *     http://www.apache.org/licenses/LICENSE-2.0\n"
    " *\n"
    " * Unless required by applicable law or agreed to in writing, software\n"
    " * distributed under the License is distributed on an \"AS IS\" BASIS,\n"
    " * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
    " * See the License for the specific language governing permissions and\n"
    " * limitations under the License.\n"
    " */\n"
    "\n"
    "#pragma once\n"
    "\n"
    "#include <cstdint>\n"
    "#include \"velox/experimental/wave/common/Cuda.h\"\n"
    "#include \"velox/experimental/wave/common/HashTable.h\"\n"
    "#include \"velox/experimental/wave/exec/ErrorCode.h\"\n"
    "#include \"velox/experimental/wave/vector/Operand.h\"\n"
    "\n"
    "/// Wave common instruction set. Instructions run a thread block wide\n"
    "/// and offer common operations like arithmetic, conditionals,\n"
    "/// filters, hash lookups, etc. Several vectorized operators can fuse\n"
    "/// into one instruction stream. Instruction streams may use shared\n"
    "/// memory depending on the instruction mix. The shared memory is to\n"
    "/// be allocated dynamically at kernel invocation.\n"
    "namespace facebook::velox::wave {\n"
    "\n"
    "/// Opcodes for common instruction set. First all instructions that\n"
    "/// do not have operand type variants, then all the ones that\n"
    "/// do. For type templated instructions, the case label is opcode *\n"
    "/// numTypes + type, so these must be last in oredr not to conflict.\n"
    "enum class OpCode {\n"
    "  // First all OpCodes that have no operand type specialization.\n"
    "  kFilter = 0,\n"
    "  kWrap,\n"
    "  kLiteral,\n"
    "  kNegate,\n"
    "  kAggregate,\n"
    "  kReadAggregate,\n"
    "  kReturn,\n"
    "\n"
    "  // From here, only OpCodes that have variants for scalar types.\n"
    "  kPlus_BIGINT,\n"
    "  kLT_BIGINT\n"
    "};\n"
    "\n"
    "constexpr int32_t kLastScalarKind = static_cast<int32_t>(WaveTypeKind::HUGEINT);\n"
    "\n"
    "struct IBinary {\n"
    "  OperandIndex left;\n"
    "  OperandIndex right;\n"
    "  OperandIndex result;\n"
    "  // If set, apply operation to lanes where there is a non-zero byte in this.\n"
    "  OperandIndex predicate{kEmpty};\n"
    "};\n"
    "\n"
    "struct IFilter {\n"
    "  OperandIndex flags;\n"
    "  OperandIndex indices;\n"
    "};\n"
    "\n"
    "struct IWrap {\n"
    "  // The indices to wrap on top of 'columns'.\n"
    "  OperandIndex indices;\n"
    "  int32_t numColumns;\n"
    "\n"
    "  // The columns to wrap.\n"
    "  OperandIndex* columns;\n"
    "};\n"
    "\n"
    "struct ILiteral {\n"
    "  OperandIndex literal;\n"
    "  OperandIndex result;\n"
    "  OperandIndex predicate;\n"
    "};\n"
    "\n"
    "struct INegate {\n"
    "  OperandIndex value;\n"
    "  OperandIndex result;\n"
    "  OperandIndex predicate;\n"
    "};\n"
    "struct IReturn {};\n"
    "\n"
    "enum class AggregateOp : uint8_t { kSum };\n"
    "\n"
    "/// Device-side state for group by\n"
    "struct DeviceAggregation {\n"
    "  /// hash table, nullptr if no grouping keys.\n"
    "  GpuHashTableBase* table{nullptr};\n"
    "\n"
    "  // Byte size of a rowm rounded to next 8.\n"
    "  int32_t rowSize = 0;\n"
    "\n"
    "  /// Allocator for variable llength accumulators, if not provided by 'table'.\n"
    "  RowAllocator* allocator{nullptr};\n"
    "\n"
    "  char* singleRow{nullptr};\n"
    "\n"
    "  /// Number of int64_t* in groupResultRows. One for each potential\n"
    "  /// streamIdx of reading kernel.\n"
    "  int32_t numReadStreams{0};\n"
    "\n"
    "  /// Pointers to group by result row arrays. Subscripts is\n"
    "  /// '[streamIdx][row + 1]'. Element 0 is the row count.\n"
    "  uintptr_t** resultRowPointers{nullptr};\n"
    "};\n"
    "\n"
    "/// Parameters for creating/updating a group by.\n"
    "struct AggregationControl {\n"
    "  /// Pointer to page-aligned DeviceAggregation.\n"
    "  DeviceAggregation* head;\n"
    "\n"
    "  /// Size of block starting at 'head'. Must be set on first setup.\n"
    "  int64_t headSize{0};\n"
    "\n"
    "  /// For a rehashing command, old bucket array.\n"
    "  void* oldBuckets{nullptr};\n"
    "\n"
    "  /// Count of buckets starting at oldBuckets for rehash.\n"
    "  int64_t numOldBuckets{0};\n"
    "\n"
    "  /// Size of single row allocation.\n"
    "  int32_t rowSize{0};\n"
    "};\n"
    "\n"
    "struct IUpdateAgg {\n"
    "  AggregateOp op;\n"
    "  // Offset of null indicator byte on accumulator row.\n"
    "  int32_t nullOffset;\n"
    "  // Offset of accumulator on accumulator row. Aligned at 8.\n"
    "  int32_t accumulatorOffset;\n"
    "  OperandIndex arg1{kEmpty};\n"
    "  OperandIndex arg2{kEmpty};\n"
    "  OperandIndex result{kEmpty};\n"
    "};\n"
    "\n"
    "struct IAggregate {\n"
    "  uint16_t numKeys;\n"
    "  uint16_t numAggregates;\n"
    "  // Serial is used in BlockStatus to identify 'this' for continue.\n"
    "  uint8_t serial;\n"
    "  /// Index of the state in operator states.\n"
    "  uint8_t stateIndex;\n"
    "  /// Position of status return block in operator status returned to host.\n"
    "  InstructionStatus status;\n"
    "  //  'numAggregates' Updates followed by key 'numKeys' key operand indices.\n"
    "  IUpdateAgg* aggregates;\n"
    "};\n"
    "\n"
    "struct AggregateReturn {\n"
    "  /// Count of rows in the table. Triggers rehash when high enough.\n"
    "  int64_t numDistinct;\n"
    "};\n"
    "\n"
    "struct Instruction {\n"
    "  OpCode opCode;\n"
    "  union {\n"
    "    IBinary binary;\n"
    "    IFilter filter;\n"
    "    IWrap wrap;\n"
    "    ILiteral literal;\n"
    "    INegate negate;\n"
    "    IAggregate aggregate;\n"
    "  } _;\n"
    "};\n"
    "\n"
    "struct ThreadBlockProgram {\n"
    "  // Shared memory needed for block. The kernel is launched with max of this\n"
    "  // across the ThreadBlockPrograms.\n"
    "  int32_t sharedMemorySize{0};\n"
    "  int32_t numInstructions;\n"
    "  // Array of instructions. Ends in a kReturn.\n"
    "  Instruction* instructions;\n"
    "};\n"
    "\n"
    "/// Thread block wide status in Wave kernels\n"
    "struct WaveShared {\n"
    "  /// per lane status and row count.\n"
    "  BlockStatus* status;\n"
    "  Operand** operands;\n"
    "  void** states;\n"
    "\n"
    "  /// Every wrap in the kernel will also wrap these otherwise not accessed\n"
    "  /// Operands.\n"
    "  OperandIndex extraWraps;\n"
    "  int16_t numExtraWraps;\n"
    "\n"
    "  /// True if continuing the first instruction. The instruction will\n"
    "  /// pick up its lane status from blockStatus or an\n"
    "  /// instruction-specific source. The instruction must clear this\n"
    "  /// before executing the next instruction.\n"
    "  bool isContinue;\n"
    "\n"
    "  /// True if some lane needs a continue. Used inside a kernel to\n"
    "  /// indicate that the grid level status should be set to indicate\n"
    "  /// continue. Reset before end of instruction.\n"
    "  bool hasContinue;\n"
    "\n"
    "  /// If true, all threads in block return before starting next instruction.\n"
    "  bool stop;\n"
    "  int32_t blockBase;\n"
    "  int32_t numRows;\n"
    "  /// Number of blocks for the program. Return statuses are at\n"
    "  /// '&blockStatus[numBlocks']\n"
    "  int32_t numBlocks;\n"
    "\n"
    "  /// Number of items in blockStatus covered by each TB.\n"
    "  int16_t numRowsPerThread;\n"
    "\n"
    "  int16_t streamIdx;\n"
    "\n"
    "  // Scratch data area. Size depends on shared memory size for instructions.\n"
    "  // Align 8.\n"
    "  int64_t data;\n"
    "};\n"
    "\n"
    "/// Parameters for a Wave kernel. All pointers are device side readable.\n"
    "struct KernelParams {\n"
    "  /// The first thread block with the program. Subscript is blockIdx.x.\n"
    "  int32_t* blockBase{nullptr};\n"
    "  // The ordinal of the program. All blocks with the same program have the same\n"
    "  // number here. Subscript is blockIdx.x. For compiled kernels, this gives the\n"
    "  // branch to follow for the TB at blockIdx.x.\n"
    "  int32_t* programIdx{nullptr};\n"
    "\n"
    "  // The TB program for each exe. The subscript is programIdx[blockIdx.x].\n"
    "  ThreadBlockProgram** programs{nullptr};\n"
    "\n"
    "  /// The instruction where to start the execution. If nullptr,\n"
    "  /// 0. Otherwise subscript is programIdx. The active lanes are given\n"
    "  /// in 'blockStatus'. Used when restarting program at a specific\n"
    "  /// instruction, e.g. after allocating new memory on host. nullptr means first\n"
    "  /// launch, starting at 0.\n"
    "  int32_t* startPC{nullptr};\n"
    "\n"
    "  // For each exe, the start of the array of Operand*. Instructions reference\n"
    "  // operands via offset in this array. The subscript is\n"
    "  // programIdx[blockIdx.x].\n"
    "  Operand*** operands{nullptr};\n"
    "\n"
    "  // the status return block for each TB. The subscript is blockIdx.x -\n"
    "  // (blockBase[blockIdx.x] / kBlockSize). Shared between all programs.\n"
    "  BlockStatus* status{nullptr};\n"
    "\n"
    "  // Address of global states like hash tables. Subscript is 'programIdx' and\n"
    "  // next subscript is state id in the instruction.\n"
    "  void*** operatorStates;\n"
    "\n"
    "  /// first operand index for extra wraps. 'numExtraWraps' next\n"
    "  /// operands get wrapped by all wraps in the kernel.\n"
    "  OperandIndex extraWraps{0};\n"
    "  int16_t numExtraWraps{0};\n"
    "\n"
    "  /// Number of blocks in each program. gridDim.x can be a multiple if many\n"
    "  /// programs in launch.\n"
    "  int32_t numBlocks{0};\n"
    "\n"
    "  /// Number of elements of blockStatus covered by each TB.\n"
    "  int16_t numRowsPerThread{1};\n"
    "\n"
    "  /// Id of stream <stream ordinal within WaveDriver> + (<driverId of\n"
    "  /// WaveDriver> * <number of Drivers>.\n"
    "  int16_t streamIdx{0};\n"
    "};\n"
    "\n"
    "/// Returns the shared memory size for instruction for kBlockSize.\n"
    "int32_t instructionSharedMemory(const Instruction& instruction);\n"
    "\n"
    "/// A stream for invoking ExprKernel.\n"
    "class WaveKernelStream : public Stream {\n"
    " public:\n"
    "  /// Enqueus an invocation of ExprKernel for 'numBlocks' b\n"
    "  /// tBs. 'blockBase' is the ordinal of the TB within the TBs with\n"
    "  /// the same program.  'programIdx[blockIndx.x]' is the index into\n"
    "  /// 'programs' for the program of the TB. 'operands[i]' is the start\n"
    "  /// of the Operand array for 'programs[i]'. status[blockIdx.x] is\n"
    "  /// the return status for each TB. 'sharedSize' is the per TB bytes\n"
    "  /// shared memory to be reserved at launch.\n"
    "  void call(\n"
    "      Stream* alias,\n"
    "      int32_t numBlocks,\n"
    "      int32_t sharedSize,\n"
    "      KernelParams& params);\n"
    "\n"
    "  /// Sets up or updates an aggregation.\n"
    "  void setupAggregation(AggregationControl& op);\n"
    "\n"
    " private:\n"
    "  // Debug implementation of call() where each instruction is a separate kernel\n"
    "  // launch.\n"
    "  void callOne(\n"
    "      Stream* alias,\n"
    "      int32_t numBlocks,\n"
    "      int32_t sharedSize,\n"
    "      KernelParams& params);\n"
    "};\n"
    "\n"
    "} // namespace facebook::velox::wave\n");
registerHeader("velox/experimental/wave/common/hashTable.h\n");
registerHeader("velox/experimental/wave/common/hashTable.cuh\n");
registerHeader("velox/experimental/wave/common/hash.cuh\n");
registerHeader(
    "velox/experimental/wave/common/StringView.cuh\n"
    "/*\n"
    " * Copyright (c) Facebook, Inc. and its affiliates.\n"
    " *\n"
    " * Licensed under the Apache License, Version 2.0 (the \"License\");\n"
    " * you may not use this file except in compliance with the License.\n"
    " * You may obtain a copy of the License at\n"
    " *\n"
    " *     http://www.apache.org/licenses/LICENSE-2.0\n"
    " *\n"
    " * Unless required by applicable law or agreed to in writing, software\n"
    " * distributed under the License is distributed on an \"AS IS\" BASIS,\n"
    " * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
    " * See the License for the specific language governing permissions and\n"
    " * limitations under the License.\n"
    " */\n"
    "\n"
    "#pragma once\n"
    "\n"
    "#include \"velox/experimental/wave/common/StringView.h\"\n"
    "\n"
    "namespace facebook::velox::wave {\n"
    "\n"
    "__device__ StringView StringView::cas(StringView compare, StringView val) {\n"
    "  StringView old;\n"
    "  old.data_ = atomicCAS(&data_, compare.data_, val.data_);\n"
    "  return old;\n"
    "}\n"
    "\n"
    "} // namespace facebook::velox::wave\n");
} // namespace facebook::velox::wave
